Fix `Context.trigger_typing()` not being an attribute anymore on dpy v2.1.0
phenom4n4n/phen-cogs pull request #152
Opened 2023-01-08 17:26 UTC by japandotorg

2023-01-08 23:23 UTC, phenom4n4n commented on lock/lock.py
> +            return
The try/except clause here absorbs all Forbidden errors. I think it's ok to just remove it.

2023-01-08 23:23 UTC, phenom4n4n commented on lock/lock.py
>              return
Same issue with the try/except clause as above.

2023-01-08 23:23 UTC, phenom4n4n commented on lock/lock.py
> +                await ctx.send(msg)
This should be outside of the `ctx.typing()` context manager.

2023-01-08 23:23 UTC, phenom4n4n commented on lock/lock.py
>              return
Same issue with the try/except clause as above.

2023-01-08 23:23 UTC, phenom4n4n commented on lock/lock.py
>              return
Same issue with the try/except clause as above.

2023-01-08 23:23 UTC, phenom4n4n commented on lock/lock.py
> +                await ctx.send(msg)
This should be outside of the `ctx.typing()` context manager.

2023-01-08 23:23 UTC, phenom4n4n commented on pfpimgen/pfpimgen.py
> +            async with ctx.typing():
Why is there a `ctx.typing()` context manager nested within another one?

2023-01-08 23:23 UTC, phenom4n4n commented on pfpimgen/pfpimgen.py
> +                await ctx.send(file=image)
This should be outside of the `ctx.typing()` context manager.

2023-04-24 19:33 UTC, japandotorg commented
Guess that's it, unless I'm missing something again.

2023-05-01 04:12 UTC, phenom4n4n requested changes

2023-05-01 04:12 UTC, phenom4n4n commented on baron/baron.py
> +        async with ctx.typing():
This change is not necessary - `await ctx.typing()` is proper usage as documented in the discord.py docs.

2023-05-01 04:12 UTC, phenom4n4n commented on lock/lock.py
> -            await ctx.trigger_typing()
Please use `await ctx.typing()` and retain the try/except block rather than using a context manager.

2023-05-01 04:12 UTC, phenom4n4n commented on lock/lock.py
> -            await ctx.trigger_typing()
Please use `await ctx.typing()` and retain the try/except block rather than using a context manager.

2023-05-01 04:12 UTC, phenom4n4n commented on lock/lock.py
> -            await ctx.trigger_typing()
Please use `await ctx.typing()` and retain the try/except block rather than using a context manager.

2023-05-01 04:12 UTC, phenom4n4n commented on lock/lock.py
> -            await ctx.trigger_typing()
Please use `await ctx.typing()` and retain the try/except block rather than using a context manager.

2023-05-09 03:18 UTC, phenom4n4n approved these changes

2023-05-09 03:18 UTC, phenom4n4n approved these changes

2023-05-09 03:18 UTC, merged